use std::path::Path;

use anyhow::Result;
use camino::Utf8PathBuf;
use serde::{Deserialize, Serialize};

pub trait LanguagePlugin: Send + Sync {
    fn id(&self) -> &'static str;

    fn display_name(&self) -> &'static str;

    fn capabilities(&self) -> Vec<PluginCapability> {
        vec![
            PluginCapability::TargetDiscovery,
            PluginCapability::GeneratedTests,
            PluginCapability::ExistingTests,
            PluginCapability::Coverage,
            PluginCapability::RegressionPromotion,
        ]
    }

    fn detect_project(&self, root: &Path) -> Result<ProjectInfo>;

    fn discover_targets(&self, root: &Path) -> Result<Vec<VerificationTarget>>;

    fn generate_tests(
        &self,
        target: &VerificationTarget,
        plan: &VerificationPlan,
    ) -> Result<Vec<GeneratedArtifact>>;

    fn run_tests(
        &self,
        root: &Path,
        artifacts: &[GeneratedArtifact],
        plan: &VerificationPlan,
    ) -> Result<TestRunResult>;

    fn collect_coverage(&self, root: &Path) -> Result<Option<CoverageReport>>;

    fn promote_regression(
        &self,
        _root: &Path,
        _report: &VerificationReport,
        finding: &Failure,
        index: usize,
    ) -> Result<Vec<GeneratedArtifact>> {
        let language = finding_language(finding).unwrap_or_else(|| self.id().to_string());
        let mut contents = String::from("# Regression Promotion\n\n");
        contents.push_str("Generated by veritas. Review before committing.\n\n");
        contents.push_str(&format!("- Finding: {}\n", finding.message));
        contents.push_str(&format!("- Severity: {:?}\n", finding.severity));
        contents.push_str(&format!("- Command: `{}`\n", finding.command));
        if let Some(target_id) = &finding.target_id {
            contents.push_str(&format!("- Target: `{target_id}`\n"));
        }
        if let Some(repro) = &finding.repro {
            contents.push_str(&format!("- Repro command: `{}`\n", repro.command));
            if let Some(path) = &repro.path {
                contents.push_str(&format!("- Repro path: `{path}`\n"));
            }
            if let Some(input) = &repro.input {
                contents.push_str(&format!("- Repro input: `{}`\n", input.trim()));
            }
        }
        contents.push_str("\n## Next Step\n\n");
        contents.push_str("This language plugin has not implemented executable regression promotion yet. Add a handwritten test owned by the target package, then rerun `veritas verify`.\n");

        Ok(vec![GeneratedArtifact {
            id: format!("{language}-promoted-regression-{index}"),
            language: language.clone(),
            kind: ArtifactKind::RegressionTest,
            target_id: finding
                .target_id
                .clone()
                .unwrap_or_else(|| format!("{language}:unknown")),
            path: Utf8PathBuf::from(format!(
                ".veritas/regressions/promoted/{language}_{index}.md"
            )),
            contents,
            description: "Generic regression promotion guidance".to_string(),
            status: ArtifactStatus::Planned,
        }])
    }
}

fn finding_language(finding: &Failure) -> Option<String> {
    finding
        .target_id
        .as_deref()
        .and_then(|target_id| target_id.split_once(':').map(|(language, _)| language))
        .map(ToString::to_string)
}

pub trait VerificationPlanner: Send + Sync {
    fn plan(&self, project: &ProjectInfo, target: &VerificationTarget) -> Result<VerificationPlan>;
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ProjectInfo {
    pub language: String,
    pub name: String,
    pub root: Utf8PathBuf,
    pub manifests: Vec<Utf8PathBuf>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationTarget {
    pub id: String,
    pub language: String,
    pub kind: TargetKind,
    pub path: Utf8PathBuf,
    pub symbol: Option<String>,
    pub signature: Option<String>,
    pub line_range: Option<LineRange>,
    pub description: String,
    pub risk: RiskLevel,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LineRange {
    pub start: usize,
    pub end: usize,
}

impl LineRange {
    pub fn overlaps(&self, other: &LineRange) -> bool {
        self.start <= other.end && other.start <= self.end
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TargetKind {
    Project,
    Package,
    File,
    Function,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum RiskLevel {
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum FailureSeverity {
    Info,
    Warning,
    Error,
    Critical,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationPlan {
    pub target_id: String,
    pub strategies: Vec<VerificationStrategy>,
    pub budget_seconds: u64,
    pub write_generated_tests: bool,
    pub run_existing_tests: bool,
    pub run_generated_tests: bool,
    pub fail_on_generated_test_failure: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum VerificationStrategy {
    ExistingTests,
    UnitTests,
    PropertyTests,
    Fuzzing,
    DifferentialTests,
    MutationChecks,
    CoverageFeedback,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct GeneratedArtifact {
    pub id: String,
    pub language: String,
    pub kind: ArtifactKind,
    pub target_id: String,
    pub path: Utf8PathBuf,
    pub contents: String,
    pub description: String,
    pub status: ArtifactStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactKind {
    UnitTest,
    PropertyTest,
    FuzzHarness,
    HarnessIndex,
    MutationCheck,
    CoverageFeedback,
    DifferentialBaseline,
    ReproCase,
    PackageAwareness,
    PackageGraph,
    SymbolGraph,
    ChangeDigest,
    AiFeedback,
    CandidatePatch,
    FindingBaseline,
    RegressionTest,
    DifferentialReplay,
    EvolutionPlan,
    AssertionCandidate,
    CorpusEntry,
    ReplayResult,
    BudgetPlan,
    ConfidenceScore,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum PluginCapability {
    TargetDiscovery,
    SymbolGraph,
    GeneratedTests,
    ExistingTests,
    PropertyTests,
    Fuzzing,
    MutationChecks,
    Coverage,
    DifferentialReplay,
    CorpusReplay,
    RegressionPromotion,
    ResourceBudgets,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactStatus {
    Planned,
    Written,
    Skipped,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TestRunResult {
    pub language: String,
    pub status: RunStatus,
    pub commands: Vec<CommandRecord>,
    pub failures: Vec<Failure>,
    pub duration_ms: u128,
    #[serde(default)]
    pub quality: VerificationQuality,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RunStatus {
    Passed,
    Failed,
    Skipped,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandRecord {
    pub program: String,
    pub args: Vec<String>,
    pub cwd: Utf8PathBuf,
    pub exit_code: Option<i32>,
    pub status: RunStatus,
    pub stdout: String,
    pub stderr: String,
    pub duration_ms: u128,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Failure {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    pub message: String,
    #[serde(default = "default_failure_severity")]
    pub severity: FailureSeverity,
    pub target_id: Option<String>,
    pub artifact_id: Option<String>,
    pub command: String,
    pub stdout_excerpt: String,
    pub stderr_excerpt: String,
    pub repro: Option<ReproCase>,
}

fn default_failure_severity() -> FailureSeverity {
    FailureSeverity::Error
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ReproCase {
    pub command: String,
    pub input: Option<String>,
    pub path: Option<Utf8PathBuf>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AssertionCandidate {
    pub language: String,
    pub target_id: String,
    pub finding_id: Option<String>,
    pub source: AssertionSource,
    pub domain: AssertionDomain,
    pub title: String,
    pub seed_inputs: Vec<String>,
    pub expected_behavior: String,
    pub replay_command: Option<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AssertionSource {
    MutationSurvivor,
    FuzzRepro,
    GeneratedTestFailure,
    DifferentialReplay,
    CoverageGap,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum AssertionDomain {
    AuthPermission,
    Money,
    Parsing,
    Serialization,
    ErrorHandling,
    Boundary,
    General,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CorpusEntry {
    pub language: String,
    pub target_id: String,
    pub finding_id: Option<String>,
    pub source: AssertionSource,
    pub input: Option<String>,
    pub path: Option<Utf8PathBuf>,
    pub replay_command: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CommandBudget {
    pub language: String,
    pub target_id: String,
    pub budget_seconds: u64,
    pub max_concurrency: usize,
    pub resource_limits: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ConfidenceScore {
    pub score: u8,
    pub grade: ConfidenceGrade,
    pub summary: String,
    pub positive_signals: Vec<String>,
    pub risks: Vec<String>,
    pub recommended_next_steps: Vec<String>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConfidenceGrade {
    Low,
    Medium,
    High,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CoverageReport {
    pub tool: String,
    pub summary: String,
    pub files: Vec<CoverageFile>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct CoverageFile {
    pub path: Utf8PathBuf,
    pub line_coverage_percent: Option<u8>,
    pub uncovered_ranges: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationReport {
    pub project: Option<ProjectInfo>,
    pub targets: Vec<VerificationTarget>,
    pub plan: Option<VerificationPlan>,
    pub artifacts: Vec<GeneratedArtifact>,
    pub runs: Vec<TestRunResult>,
    pub coverage: Vec<CoverageReport>,
    pub findings: Vec<Failure>,
    #[serde(default)]
    pub quality: VerificationQuality,
    pub suggested_next_steps: Vec<String>,
}

impl VerificationReport {
    pub fn empty() -> Self {
        Self {
            project: None,
            targets: Vec::new(),
            plan: None,
            artifacts: Vec::new(),
            runs: Vec::new(),
            coverage: Vec::new(),
            findings: Vec::new(),
            quality: VerificationQuality::default(),
            suggested_next_steps: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct VerificationQuality {
    pub mutation: MutationMetrics,
    pub property: PropertyMetrics,
    pub fuzz: FuzzMetrics,
    #[serde(default)]
    pub regression: RegressionMetrics,
    #[serde(default)]
    pub replay: ReplayMetrics,
    #[serde(default)]
    pub budget: BudgetMetrics,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct MutationMetrics {
    pub generated: usize,
    pub executed: usize,
    pub killed: usize,
    pub survived: usize,
    pub skipped: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub score_percent: Option<u8>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct PropertyMetrics {
    pub generated_artifacts: usize,
    pub failed_generated_tests: usize,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct FuzzMetrics {
    pub generated_harnesses: usize,
    pub targets_executed: usize,
    pub failures: usize,
    pub persisted_repros: usize,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct RegressionMetrics {
    pub assertion_candidates: usize,
    pub promoted_scaffolds: usize,
    pub corpus_entries: usize,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct ReplayMetrics {
    pub manifests: usize,
    pub targets: usize,
    pub cases: usize,
    pub results: usize,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq, Eq)]
pub struct BudgetMetrics {
    pub budget_plans: usize,
    pub skipped_commands: usize,
    pub timed_out_commands: usize,
}
