[package]
name = "veritas-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for veritas"

[[bin]]
name = "veritas"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
veritas-core = { path = "../veritas-core" }
veritas-go = { path = "../veritas-go" }
veritas-plugin-api = { path = "../veritas-plugin-api" }
veritas-report = { path = "../veritas-report" }
veritas-rust = { path = "../veritas-rust" }

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.10"
