[package]
name = "veritas-go"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Go language plugin for veritas"

[dependencies]
anyhow.workspace = true
camino.workspace = true
serde.workspace = true
serde_json.workspace = true
tree-sitter.workspace = true
tree-sitter-go = "0.25.0"
veritas-core = { version = "0.1.0", path = "../veritas-core" }
veritas-plugin-api = { version = "0.1.0", path = "../veritas-plugin-api" }
walkdir.workspace = true
